# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

# These configurations have been inspired by https://github.com/cloudify-cosmo/cloudify-common/blob/master/.circleci/config.yml
version: 2

defaults:
  - &test_defaults
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
jobs:
  flake8:
    <<: *test_defaults
    steps:
      - checkout
      - run:
          name: Install tox
          command: sudo pip install flake8
      - run:
          name: flake8
          command: |
            flake8
      - store_artifacts:
          path: test-reports
          destination: test-reports
  pythontests:
    <<: *test_defaults
    steps:
      - checkout
      - run:
          command: sudo pip install -rrequirements.txt -rtest-requirements.txt
      - run:
          name: Run tests
          command: pytest test_all.py --cov=./
      - store_artifacts:
          path: test-reports
          destination: test-reports
      - run:
          name: Upload coverage
          command: |
            codecov -t $CODECOV_TOKEN
workflows:
  version: 2
  build_and_test:
    jobs:
      - flake8
      # Other tests go here
      - pythontests
